### ISSUE TITLE
Stops working after moving to new Outlook Desktop App

### ISSUE THREAD

**Issue by amaral-rc** [mdgrs-mei/outlook-taskbar-notifier#6]
Hey 
This notifier has been a lifesaver.
Unfortunately moving to the new outlook app means I cannot get this one to work.
Is there a setting I can adjust?
Thanks

**Comment by mdgrs-mei** [comment]
Hello @amaral-rc ,

Do you mean [the new Outlook for Windows](https://support.microsoft.com/en-us/office/getting-started-with-the-new-outlook-for-windows-656bb8d9-5a60-49b2-a98b-ba7822bc7627)?

Unfortunately, the new app does not allow COM object access which this notifier heavily relies on. I keep using the old desktop app for this reason and haven't found a good solution.

**Comment by mdgrs-mei** [comment]
Closing as answered. Thank you.
